export const RECEIVED_PHONES = 'RECEIVED_PHONES'
export const FILTER_PHONE_BY_KEYWORD = 'FILTER_PHONE_BY_KEYWORD'
export const SORT_PHONE = 'SORT_PHONE'
export const RECEIVED_PHONE_DETAIL = 'RECEIVED_PHONE_DETAIL'